# -*- mode: python ; coding: utf-8 -*-
# Folder build — faster startup, recommended for daily use

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config/theme_config.txt',   '.'),
        ('config/layout_config.txt',  '.'),
        ('config/font_size.txt',      '.'),
        ('config/sample_import.json', '.'),
        ('assets', 'assets'),
        ('web_app/index.html', 'web_app'),
        ('core',    'core'),
        ('ui',      'ui'),
        ('widgets', 'widgets'),
    ],
    hiddenimports=[
        # ttkbootstrap
        'ttkbootstrap',
        'ttkbootstrap.constants',
        'ttkbootstrap.style',
        'ttkbootstrap.themes',
        'ttkbootstrap.themes.standard',
        'ttkbootstrap.widgets',
        'ttkbootstrap.dialogs',
        'ttkbootstrap.dialogs.dialogs',
        'ttkbootstrap.scrolled',
        'ttkbootstrap.tableview',
        'ttkbootstrap.tooltip',
        'ttkbootstrap.validation',
        'ttkbootstrap.localization',
        # Pillow
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL._imaging',
        'PIL._imagingtk',
        'PIL.ImageColor',
        'PIL.ImageFilter',
        'PIL.ImageOps',
        # stdlib
        'sqlite3',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.simpledialog',
        'csv',
        'json',
        'shutil',
        'tempfile',
        'math',
        'datetime',
        'hashlib',
        'subprocess',
        'uuid',
        'webbrowser', 'base64', 'threading', 'logging', 're',
        # cryptography — license manager
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        # reportlab — developer PDF generator
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.colors',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.platypus',
        'reportlab.pdfgen',
        # App core
        'core.alert_colors',
        'core.customer_service',
        'core.font_config',
        'core.font_updater',
        'core.input_controller',
        'core.layout_config',
        'core.scroll_manager',
        'core.export_manager',
        'core.license_manager',
        # openpyxl
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.writer.excel',
        'et_xmlfile',
        # UI pages
        'ui.billing',
        'ui.customers',
        'ui.import_purchases',
        'ui.inventory',
        'ui.purchase',
        'ui.purchase_history',
        'ui.sales_history',
        'ui.settings',
        'ui.shelf_management',
        # Widgets
        'widgets.activation_dialog',
        'widgets.bill_edit',
        'widgets.bill_preview',
        'widgets.searchable_combo',
        'widgets.two_step_medicine_combo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'numpy', 'pandas', 'scipy', 'wx', 'PyQt5', 'PyQt6'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='VeterinaryManagementSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/satpuda_logo.ico',
)

# ── Folder build — all files collected into dist/VeterinaryManagementSystem/ ──
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='VeterinaryManagementSystem',
)
