# -*- mode: python ; coding: utf-8 -*-
# Folder build — faster startup, recommended for daily use

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config/theme_config.txt',   'config'),
        ('config/layout_config.txt',  'config'),
        ('config/font_size.txt',      'config'),
        ('config/sample_import.json', 'config'),
        ('config/backup_creds.dat',   'config'),
        ('config/backup_config.dat',  'config'),
        ('config/backup_slots.dat',   'config'),
        ('config/expiry.dat',         'config'),
        ('config/activation.dat',     'config'),
        ('config/app_mode.txt',       'config'),
        ('assets', 'assets'),
        ('web_app', 'web_app'),
        ('core',    'core'),
        ('ui',      'ui'),
        ('widgets', 'widgets'),
    ],
    hiddenimports=[
        # ttkbootstrap
        'ttkbootstrap',
        'ttkbootstrap.constants',
        'ttkbootstrap.style',
        'ttkbootstrap.themes',
        'ttkbootstrap.themes.standard',
        'ttkbootstrap.widgets',
        'ttkbootstrap.dialogs',
        'ttkbootstrap.dialogs.dialogs',
        'ttkbootstrap.scrolled',
        'ttkbootstrap.tableview',
        'ttkbootstrap.tooltip',
        'ttkbootstrap.validation',
        'ttkbootstrap.localization',
        # Pillow
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL._imaging',
        'PIL._imagingtk',
        'PIL.ImageColor',
        'PIL.ImageFilter',
        'PIL.ImageOps',
        # stdlib
        'sqlite3',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'tkinter.simpledialog',
        'csv',
        'json',
        'shutil',
        'tempfile',
        'math',
        'datetime',
        'hashlib',
        'subprocess',
        'uuid',
        'webbrowser', 'base64', 'threading', 'logging', 're',
        # cryptography — license manager
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        # reportlab — developer PDF generator
        'reportlab',
        'reportlab.lib',
        'reportlab.lib.pagesizes',
        'reportlab.lib.colors',
        'reportlab.lib.styles',
        'reportlab.lib.units',
        'reportlab.platypus',
        'reportlab.pdfgen',
        # App core
        'core.alert_colors', 'core.app_setup', 'core.backup_manager',
        'core.billing_service', 'core.calc_engine', 'core.customer_service',
        'core.db_setup', 'core.export_manager', 'core.font_config',
        'core.font_updater', 'core.input_controller', 'core.layout_config',
        'core.license_manager', 'core.purchase_calculator', 'core.purchase_importer',
        'core.purchase_service', 'core.scroll_manager', 'core.themed_messagebox',
        # UI pages
        'ui.billing', 'ui.billing.billing', 'ui.billing.billing_form',
        'ui.billing.billing_nav', 'ui.billing.bill_edit',
        'ui.inventory', 'ui.inventory.inventory', 'ui.inventory.inventory_dialogs',
        'ui.purchase', 'ui.purchase.purchase', 'ui.purchase.purchase_form',
        'ui.purchase.purchase_nav', 'ui.purchase.purchase_history',
        'ui.purchase.purchase_history_edit',
        'ui.returns', 'ui.returns.sales_return', 'ui.returns.purchase_return',
        'ui.sales', 'ui.sales.sales_history', 'ui.sales.sales_history_actions',
        'ui.sales.sales_history_exports',
        'ui.settings', 'ui.settings.settings', 'ui.settings.import_purchase_dialog',
        'ui.settings.settings_tabs', 'ui.settings.settings_tabs.database_tab',
        'ui.settings.settings_tabs.doctors_tab', 'ui.settings.settings_tabs.layout_tab',
        'ui.settings.settings_tabs.ledger_tab', 'ui.settings.settings_tabs.misc_tabs',
        'ui.settings.settings_tabs.payment_tab', 'ui.settings.settings_tabs.pharmacy_tab',
        'ui.settings.settings_tabs.suppliers_tab',
        'ui.settings.settings_tabs.customer_payment_tab',
        'ui.shared', 'ui.shared.customers', 'ui.shared.home_page',
        'ui.shared.import_from_mobile', 'ui.shared.import_purchases',
        'ui.shared.shelf_management',
        # Widgets
        'widgets.activation_dialog', 'widgets.bill_edit', 'widgets.bill_preview',
        'widgets.searchable_combo', 'widgets.two_step_medicine_combo',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'numpy', 'pandas', 'scipy', 'wx', 'PyQt5', 'PyQt6'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='VeterinaryManagementSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/satpuda_logo.ico',
)

# ── Folder build — all files collected into dist/VeterinaryManagementSystem/ ──
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='VeterinaryManagementSystem',
)
