"""The signed licence — "the seal". The expiry stops being a local fact.

WHAT WAS WRONG
--------------
A shop's expiry lived in one file on the shop's own PC, ``expiry.dat``, and the
app believed whatever it found there. Two ways to profit from that, and neither
needed any skill:

  * DELETE the file. ``_read_expiry()`` returns ``{}``, ``check_expiry()`` reads
    that as "no restriction configured" and returns False. Reinstalling gives
    the same result, because the installer's sign-up is refused for a computer
    that has already had its trial and the Offline path then activates locally
    with no expiry at all. The licence was one keystroke from permanent.
  * EDIT the file. It is encrypted, but with ``_SECRET`` -- a constant compiled
    into every copy of the build. Anyone willing to open the exe can write a new
    date rather than merely delete the old one.

And ``expiry_config.json``, which decides whether expiry is consulted at all, is
plain JSON. ``{"apply_expiry_check": false}`` in a text editor turned the whole
mechanism off.

THE OWNER'S DECISION
--------------------
Once an expiry is set at first activation -- Online or Offline -- it must not
change except from the server or from the software's own Administrator settings.
Deleting the file and reinstalling must not reset it: *"delete kelch tr aapn
internet suru karnyas sangu shakto mhanaje tech file punha yeil"* -- if they
delete it we can tell them to turn the internet on, and the same file comes back.
An offline shop needing internet once is accepted, because the installer already
needs it to download.

THE SHAPE
---------
The server decides the expiry and SIGNS it. The desktop keeps the signed blob and
verifies it before believing a word of it.

  * EDIT the date -> the signature fails -> blocked immediately.
  * COPY the blob to another PC -> the machine binding fails -> blocked.
  * DELETE the blob -> not "no restriction". No licence. The app asks for
    internet once and fetches the SAME blob back, because the server -- not the
    file -- is where the expiry lives.

THE CRYPTO, AND WHY THIS ONE
----------------------------
RSA-2048, RSASSA-PKCS#1 v1.5, SHA-256, over the exact ASCII bytes transmitted.

  * ASYMMETRIC. The build carries only the PUBLIC key. Decompiling the exe yields
    a key that can check a licence and cannot write one. An HMAC would put the
    minting secret inside every installer that can be downloaded, which is the
    same mistake the server already refused to make when it built
    ``/api/provision/trial`` rather than shipping the vendor's administrator
    password in the build.

  * PKCS#1 v1.5 rather than Ed25519 or PSS, and the reason is this file. The
    verifier has to work when ``cryptography`` does not import -- a case this
    code base has already been bitten by and still carries a fallback for (see
    ``_get_fernet`` in license_manager). A hand-written Ed25519 verifier is
    eighty lines of modular arithmetic with real traps: cofactor, canonical
    encodings, malleability. A PKCS#1 v1.5 verifier is ``pow(sig, e, n)`` and one
    comparison against the expected block -- twenty lines, no attacker-steerable
    branch, and because it compares the WHOLE block rather than parsing it, the
    lenient-parser family of bugs (Bleichenbacher '06) cannot exist in it. One
    algorithm, two implementations, no weak mode to fall into. ``_verify_raw``
    below prefers ``cryptography`` and falls back to ``_verify_stdlib``; a test
    runs both against the same blobs.

  * The signature covers ``SATPUDA1.<base64url(payload)>`` as ASCII, JWS-style,
    so no canonical-JSON agreement is needed between Node and Python. Key order,
    spacing and unicode escaping cannot break a signature.

WHAT THIS FILE WILL NOT DO
--------------------------
It will not invent an expiry, and it will not treat a missing one as permission.
The only two answers it gives are "here is a licence the server signed" and "this
computer needs internet once".
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import threading
import time
from datetime import date, datetime, timedelta, timezone

# ── The public keys this build will accept ────────────────────────────────────
#
# kid -> base64 of the SubjectPublicKeyInfo DER. A dict rather than one key so a
# replacement can be shipped in a build BEFORE the old one is retired: every PC
# in the fleet then already accepts both, and the day the server switches keys
# nothing stops working.
#
# Generated by ``node make-license-key.mjs`` on the server, which prints this
# block ready to paste. The private half never leaves that machine.
_PUBLIC_KEYS: dict[str, str] = {
    "386fbbc7a1275497": (
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkpE9nxo0oC4YPKXULoQP"
        "DG7ezF4zKj3fYy8sn0L1KORnBTgmrxldlnVLXHRE0yYeKCrxDjqshoThz+iWuO9e"
        "UZPeW/in89zxNa+k7IwUyWZYyNtqGk7Xfv+oDM4faeP/qRx7N/JNDF9BezCzRlH5"
        "5VKFhFlqEo0r+OpVQ6pJeSTLWR0psNuY9v4sLp6g6OLfns4ds99C2wcYMyFCszl/"
        "J7Hvw49P58X5XYZ/XM2PNBw3I59WWOHjY1rrzdtg1HPNTByS2mwG4kSi8dCYRm8M"
        "3nd+bbFRoRzssBlNp2dfJ/yMD2Y7w1oKUnCrbpN407vQYRayWGOHelwOZ/KTCm1C"
        "MwIDAQAB"
    ),
}

SEAL_PREFIX = "SATPUDA1"
SEAL_FILE = "license.seal"

# ── The two dates that make this shippable ────────────────────────────────────
#
# SEAL_CUTOVER tells a shop that was ALREADY RUNNING apart from a fresh install.
# An activation record older than this was written by a build that had no seal to
# fetch, so its absence is not evidence of anything.
#
# LEGACY_GRACE_UNTIL is how long such a shop keeps running exactly as it did
# before while it gets one chance to be online. It is an ABSOLUTE date compiled
# into the build, not "N days from first run" -- a first-run counter lives in
# AppData, and a counter that a delete resets is the very hole being closed here.
#
# Note what does NOT get grace: a PC with no activation record, or one activated
# after the cutover. Wiping AppData takes activation.dat with it, so the delete
# trick lands in "no licence, fetch one" on the very first launch -- today, not
# after the grace date.
SEAL_CUTOVER = "2026-09-10"
LEGACY_GRACE_UNTIL = "2026-11-30"

# ── The fresh install that has never reached the server ───────────────────────
#
# A shop signing up Offline with no internet -- or with a server that cannot
# answer, which on live is EVERY sign-up, because POST /api/provision/trial has
# returned 500 since the feature shipped -- activates locally and comes away
# with no signed licence at all. Under the rules above that is STATE_MISSING
# with no legacy grace, i.e. blocked: the installer finished, the shop was told
# it was set up, and the next launch showed "Licence not found" with no way out.
# Connecting the internet did not help either, because /api/provision/license
# can only answer for a machine the trial call has recorded.
#
# So a PC that has JUST activated and has NEVER held a licence gets the same
# window the server would have granted it -- FRESH_INSTALL_DAYS from the
# activation date, which is the server's own trial length -- and then expires
# like any other trial. Deliberately bounded, and deliberately narrow:
#
#   * it needs an activation.dat, so a wiped AppData does not qualify until the
#     shop activates again, and the delete trick still costs an activation;
#   * it needs the activation to be dated ON OR AFTER the cutover, so it cannot
#     be conjured by back-dating a record into the legacy window;
#   * it is refused outright once this PC has EVER held a verified licence
#     (``seal_ever_stored``), which is recorded inside the Fernet-encrypted
#     activation.dat -- so deleting license.seal still blocks, exactly as it did
#     before, and "delete the file, get three more days" is not a thing;
#   * STATE_TAMPERED never qualifies. An edited or borrowed blob is not a
#     missing one.
#
# Three more conditions were added on 2026-09-16, after an adversarial review
# proved the window above could be renewed by the shop itself, for ever, with no
# server and no vendor code:
#
#   * the window is measured from the FIRST activation this computer ever made
#     (``first_date``), which _write_activation now carries forward, so the
#     vendor re-activation form -- whose username and password are literals in
#     the build -- cannot re-date the record into a new window;
#   * the first date is also kept OUTSIDE activation.dat, in starter.dat, so
#     deleting the record does not delete the memory of the window; and the
#     earlier of the two always wins;
#   * a shop that has ALREADY SOLD something does not qualify at all. A fresh
#     install has no bills. This is the one condition no local delete can undo,
#     and it is what stops an expired paying shop from wiping its files to buy
#     itself three days at a time.
#
# What is deliberately still true: a computer with no shop data on it at all can
# keep granting itself three days. There is nothing on it to protect, and no
# offline check can do better -- the honest fix for that shop is the one the
# screen now offers, which is to connect once.
#
# The number must equal the server's trial window (DEFAULT_EXPIRY_DAYS in
# licenseService.js, mirrored as trial_activation.FALLBACK_TRIAL_DAYS); a build
# that granted more than the server would is a build that hands out free time.
FRESH_INSTALL_DAYS = 3

# States seal_state() can report.
STATE_SIGNED = "signed"      # a verified blob; it decides access
STATE_LEGACY = "legacy"      # pre-seal shop inside the grace window
STATE_FRESH = "fresh"        # activated here, never had a licence, inside its window
STATE_MISSING = "missing"    # no blob, no grace -> needs internet once
STATE_TAMPERED = "tampered"  # a blob that does not verify -> needs internet once

NEEDS_INTERNET_MESSAGE = (
    "This computer needs to be connected to the internet once so Satpuda can "
    "restore its licence. Connect the internet and open the software again."
)
FRESH_INSTALL_MESSAGE = (
    "This shop is running on a {days}-day starter licence because Satpuda's "
    "server could not be reached when it was set up. Connect the internet once "
    "before {until} so the full licence can be issued."
)
FRESH_INSTALL_LAPSED_MESSAGE = (
    "The {days}-day starter licence for this computer has ended. Connect the "
    "internet so Satpuda can issue the full licence, or contact Satpuda to "
    "extend it."
)
TAMPERED_MESSAGE = (
    "The licence file on this computer is not the one Satpuda issued. Connect "
    "the internet and open the software again to restore it."
)


# ── Small helpers ─────────────────────────────────────────────────────────────
def _appdata_dir() -> str:
    from core.license_manager import _appdata_dir as d

    return d()


def seal_path() -> str:
    return os.path.join(_appdata_dir(), SEAL_FILE)


def _b64url_decode(text: str) -> bytes:
    raw = str(text or "").strip().replace("-", "+").replace("_", "/")
    raw += "=" * (-len(raw) % 4)
    return base64.b64decode(raw)


def _today() -> date:
    return date.today()


def _as_date(value) -> date | None:
    try:
        return date.fromisoformat(str(value or "").strip()[:10])
    except Exception:
        return None


def keys_configured() -> bool:
    """True when this build carries at least one real public key."""
    return any(len(v or "") > 100 for v in _PUBLIC_KEYS.values())


# ── RSA verification, twice ───────────────────────────────────────────────────
#
# SHA-256 DigestInfo prefix, from RFC 8017 section 9.2 notes. Fixed bytes: this
# is the only digest algorithm the seal uses, so there is nothing to negotiate
# and nothing for a caller to steer.
_SHA256_DIGESTINFO = bytes.fromhex("3031300d060960864801650304020105000420")


def _der_read_len(buf: bytes, i: int) -> tuple[int, int]:
    n = buf[i]
    i += 1
    if n < 0x80:
        return n, i
    count = n & 0x7F
    if count == 0 or count > 4:
        raise ValueError("bad DER length")
    val = int.from_bytes(buf[i:i + count], "big")
    return val, i + count


def _rsa_numbers(spki_der: bytes) -> tuple[int, int]:
    """(modulus, exponent) out of a SubjectPublicKeyInfo DER.

    A deliberately small, strict reader. It walks the exact structure an RSA
    SPKI has and refuses anything else, rather than being a general ASN.1 parser
    -- the input is a constant compiled into this build, not something a caller
    supplies, so tolerance would buy nothing and cost surface.
    """
    i = 0
    if spki_der[i] != 0x30:
        raise ValueError("SPKI: expected SEQUENCE")
    _, i = _der_read_len(spki_der, i + 1)
    # AlgorithmIdentifier — skipped whole; the key set is ours.
    if spki_der[i] != 0x30:
        raise ValueError("SPKI: expected AlgorithmIdentifier")
    alg_len, j = _der_read_len(spki_der, i + 1)
    i = j + alg_len
    if spki_der[i] != 0x03:
        raise ValueError("SPKI: expected BIT STRING")
    bit_len, i = _der_read_len(spki_der, i + 1)
    if spki_der[i] != 0x00:
        raise ValueError("SPKI: unexpected unused bits")
    i += 1
    inner = spki_der[i:i + bit_len - 1]
    # RSAPublicKey ::= SEQUENCE { modulus INTEGER, publicExponent INTEGER }
    k = 0
    if inner[k] != 0x30:
        raise ValueError("RSAPublicKey: expected SEQUENCE")
    _, k = _der_read_len(inner, k + 1)
    vals = []
    for _ in range(2):
        if inner[k] != 0x02:
            raise ValueError("RSAPublicKey: expected INTEGER")
        n, k = _der_read_len(inner, k + 1)
        vals.append(int.from_bytes(inner[k:k + n], "big"))
        k += n
    return vals[0], vals[1]


def _verify_stdlib(spki_der: bytes, message: bytes, signature: bytes) -> bool:
    """RSASSA-PKCS1-v1_5 / SHA-256 verify, standard library only.

    The whole of it: raise the signature to the public exponent, then compare the
    result to the block that a correct signature MUST have produced. Whole-block
    equality, not a parse -- there is no "read the padding and see if it looks
    right" step to be lenient about.
    """
    try:
        n, e = _rsa_numbers(spki_der)
    except Exception:
        return False
    k = (n.bit_length() + 7) // 8
    if len(signature) != k:
        return False
    s = int.from_bytes(signature, "big")
    if s >= n:
        return False
    em = pow(s, e, n).to_bytes(k, "big")
    digest = hashlib.sha256(message).digest()
    tail = _SHA256_DIGESTINFO + digest
    ps_len = k - 3 - len(tail)
    if ps_len < 8:
        return False
    expected = b"\x00\x01" + b"\xff" * ps_len + b"\x00" + tail
    return hmac.compare_digest(em, expected)


def _verify_cryptography(spki_der: bytes, message: bytes, signature: bytes) -> bool | None:
    """The same check through ``cryptography``. None when it is not available."""
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import padding, rsa
    except Exception:
        return None
    try:
        key = serialization.load_der_public_key(spki_der)
        if not isinstance(key, rsa.RSAPublicKey):
            return False
        key.verify(signature, message, padding.PKCS1v15(), hashes.SHA256())
        return True
    except Exception:
        return False


def _verify_raw(kid: str, message: bytes, signature: bytes) -> bool:
    der_b64 = _PUBLIC_KEYS.get(str(kid or ""))
    if not der_b64:
        return False
    try:
        spki = base64.b64decode(der_b64)
    except Exception:
        return False
    via_lib = _verify_cryptography(spki, message, signature)
    if via_lib is not None:
        return bool(via_lib)
    return _verify_stdlib(spki, message, signature)


# One entry, keyed by the blob text. local_payload() runs on a status endpoint
# the desktop polls several times a second, and there is no reason to redo an
# RSA verification on bytes that have not changed. Cleared implicitly whenever
# the file does change, because the key IS the file's content.
_VERIFY_MEMO: dict[str, dict | None] = {}


def verify_blob(blob: str) -> dict | None:
    """The payload of a genuine blob, or None. Signature only — not the binding."""
    text = str(blob or "").strip()
    if text in _VERIFY_MEMO:
        memo = _VERIFY_MEMO[text]
        return dict(memo) if memo else None
    result = _verify_blob_uncached(text)
    if len(_VERIFY_MEMO) > 8:
        _VERIFY_MEMO.clear()
    _VERIFY_MEMO[text] = dict(result) if result else None
    return result


def _verify_blob_uncached(text: str) -> dict | None:
    parts = text.split(".")
    if len(parts) != 3 or parts[0] != SEAL_PREFIX:
        return None
    try:
        payload = json.loads(_b64url_decode(parts[1]).decode("utf-8"))
        signature = _b64url_decode(parts[2])
    except Exception:
        return None
    if not isinstance(payload, dict):
        return None
    if str(payload.get("alg") or "") != "RS256":
        return None
    message = f"{parts[0]}.{parts[1]}".encode("ascii")
    if not _verify_raw(payload.get("kid"), message, signature):
        return None
    return payload


# ── The machine binding ───────────────────────────────────────────────────────
_HW_KEYS = ("cpu", "board", "sysuuid", "disk")


def binding_digests() -> dict:
    """SHA-256 of each hardware component this PC can read.

    Digests, not the serial numbers. The comparison is exactly as sharp and the
    shop's disk and board serials never travel to the server or sit in its logs.
    A component that cannot be read contributes nothing rather than the digest of
    an empty string -- which would be the SAME value on every unreadable machine
    and would match all of them against each other.
    """
    try:
        from core.license_manager import _hardware_parts

        parts = _hardware_parts()
    except Exception:
        parts = {}
    out = {}
    for key in _HW_KEYS:
        val = str((parts or {}).get(key) or "").strip()
        if val:
            out[key] = hashlib.sha256(val.encode("utf-8")).hexdigest()
    return out


def binding_matches(payload: dict) -> bool:
    """Is this blob's machine THIS machine?

    Tolerant in exactly the way ``hardware_matches`` is tolerant, and for the
    same reason: this code base has already been burned by a fingerprint that
    moved when a Windows update installed a virtual adapter or a WMIC call timed
    out, and a shop locked out of its own till by a disk swap is a worse outcome
    than a licence one component looser. So: every component that BOTH sides can
    read must match, except one.

    What that still refuses is a copy. Two different computers differ in all four
    components, not one, so a blob carried to another PC on a USB stick fails.

    When nothing can be read here, the blob's device id is the fallback rather
    than a free pass. ``hardware_matches`` deliberately returns True in that case
    -- it would rather let a shop into its own till than lock it out -- but the
    same reasoning does not carry over: a blob that matches any computer with an
    unreadable fingerprint would be a licence worth copying.
    """
    if not isinstance(payload, dict):
        return False
    saved = payload.get("hwp")
    now = binding_digests()
    if isinstance(saved, dict) and saved and now:
        known = matched = 0
        for key in _HW_KEYS:
            was, is_ = str(saved.get(key) or ""), str(now.get(key) or "")
            if not was or not is_:
                continue
            known += 1
            if hmac.compare_digest(was, is_):
                matched += 1
        if known:
            return matched >= known - 1 if known > 1 else matched == 1
    # Either the blob carries no components or this machine can read none.
    saved_hw = str(payload.get("hw") or "")
    if saved_hw and now:
        try:
            from core.license_manager import _get_hardware_hash

            if hmac.compare_digest(saved_hw, str(_get_hardware_hash() or "")):
                return True
        except Exception:
            pass
    saved_dev = str(payload.get("dev") or "")
    if saved_dev:
        try:
            from core.trial_activation import device_id

            return hmac.compare_digest(saved_dev, str(device_id() or ""))
        except Exception:
            return False
    return False


# ── The rollback ratchet ──────────────────────────────────────────────────────
#
# A blob stays valid forever -- that is what a signature means. So a shop whose
# expiry the vendor SHORTENS could keep last year's generous blob and put it back.
# The counter is a high-water mark: the highest serial (the store row's
# updated_at, in seconds) this PC has ever seen. A blob read FROM DISK that is
# older than the mark is refused; a blob that arrives FRESH from the server is
# always accepted and resets the mark, so a restored database cannot lock a fleet
# out.
#
# The mark lives inside activation.dat, which is Fernet-encrypted and whose
# deletion forces a full re-activation. Deleting it to escape the ratchet
# therefore costs an activation, and an activation goes through the server.


def _read_serial_floor() -> int:
    try:
        from core.license_manager import _read_activation

        return int((_read_activation() or {}).get("lic_ser") or 0)
    except Exception:
        return 0


def _write_serial_floor(serial: int) -> None:
    try:
        from core.license_manager import _activation_path, _encrypt, _read_activation

        record = dict(_read_activation() or {})
        if not record:
            return
        if int(record.get("lic_ser") or 0) == int(serial):
            return
        record["lic_ser"] = int(serial)
        with open(_activation_path(), "wb") as fh:
            fh.write(_encrypt(record))
    except Exception:
        pass


# ── "This PC has held a real licence" ─────────────────────────────────────────
#
# One bit, and the whole safety of the fresh-install window rests on it: the
# window is only ever offered to a computer that has NEVER had a signed licence.
# Once one has been verified here, deleting the file must go back to meaning
# "connect the internet", not "here are three more days".
#
# It lives inside activation.dat, which is Fernet-encrypted and whose deletion
# forces a full re-activation -- the same place and for the same reason as the
# rollback ratchet above. A plain marker file next to it would be undone by the
# delete it exists to punish. The serial floor is read as well, because a shop
# updating from an older build has that and not this.


def _mark_seal_seen() -> None:
    try:
        from core.license_manager import _activation_path, _encrypt, _read_activation

        record = dict(_read_activation() or {})
        if not record or record.get("lic_seen"):
            return
        record["lic_seen"] = True
        with open(_activation_path(), "wb") as fh:
            fh.write(_encrypt(record))
    except Exception:
        pass


def _starter_marker_path() -> str:
    """Where the first starter window is remembered, next to activation.dat."""
    from core.license_manager import _activation_path

    return os.path.join(os.path.dirname(_activation_path()), "starter.dat")


def _read_starter_marker() -> dict:
    try:
        from core.license_manager import _decrypt

        path = _starter_marker_path()
        if not os.path.exists(path):
            return {}
        with open(path, "rb") as fh:
            return _decrypt(fh.read()) or {}
    except Exception:
        return {}


def _write_starter_marker(first_day) -> None:
    """Remember the first starter day. Never moves it later, only earlier."""
    try:
        from core.license_manager import _encrypt

        have = _as_date((_read_starter_marker() or {}).get("first"))
        if have is not None and have <= first_day:
            return
        with open(_starter_marker_path(), "wb") as fh:
            fh.write(_encrypt({"first": first_day.isoformat()}))
    except Exception:
        pass


_TRADING_CACHE: dict = {}


def _shop_already_trading() -> bool:
    """Has any shop on this computer sold or bought anything yet?

    A fresh install has not. This is the one condition a local delete cannot
    undo, so it is what keeps the starter window from becoming a renewable
    licence for a shop that is actually running (see the block above).

    Answers False for anything it cannot read: a starter window is never
    refused because a file was busy.
    """
    if "v" in _TRADING_CACHE:
        return _TRADING_CACHE["v"]
    found = False
    try:
        import sqlite3

        from core import store_manager

        for st in (store_manager.list_stores() or []):
            key = str((st or {}).get("store_key") or "")
            if not key:
                continue
            try:
                path = store_manager.get_store_db_path(key)
            except Exception:
                continue
            if not path or not os.path.exists(path):
                continue
            try:
                con = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
            except Exception:
                continue
            try:
                for table in ("sales", "purchases"):
                    try:
                        if con.execute(f"SELECT 1 FROM {table} LIMIT 1").fetchone():
                            found = True
                            break
                    except Exception:
                        continue
            finally:
                try:
                    con.close()
                except Exception:
                    pass
            if found:
                break
    except Exception:
        found = False
    _TRADING_CACHE["v"] = found
    return found


def seal_ever_stored() -> bool:
    """Has a verified licence ever been accepted on this computer?"""
    try:
        from core.license_manager import _read_activation

        record = _read_activation() or {}
    except Exception:
        return False
    if record.get("lic_seen"):
        return True
    try:
        if int(record.get("lic_ser") or 0) > 0:
            return True
    except Exception:
        pass
    # And the obvious one: a licence sitting on the disk right now.
    return bool(read_seal())


# ── Storage ───────────────────────────────────────────────────────────────────
def read_seal() -> str:
    path = seal_path()
    try:
        if not os.path.isfile(path):
            return ""
        with open(path, encoding="utf-8-sig") as fh:
            return fh.read().strip()
    except Exception:
        return ""


def store_seal(blob: str, *, fresh: bool = False) -> dict | None:
    """Verify a blob and keep it. Returns the payload, or None if it is no good.

    ``fresh`` means it came from the server just now, so it sets the ratchet
    rather than being judged by it.
    """
    payload = verify_blob(blob)
    if not payload:
        return None
    if not binding_matches(payload):
        return None
    serial = int(payload.get("ser") or 0)
    if fresh:
        _write_serial_floor(serial)
    elif serial < _read_serial_floor():
        return None
    # From here on this computer has held a real licence, so the fresh-install
    # window is closed to it for good -- even if the file is deleted a minute
    # from now. Recorded BEFORE the write, because a licence that verified is a
    # licence this PC has seen whether or not the disk accepted the file.
    _mark_seal_seen()
    try:
        path = seal_path()
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(str(blob).strip())
        os.replace(tmp, path)
    except Exception:
        # A blob that could not be written is still a valid licence for this run.
        pass
    return payload


def clear_seal() -> None:
    try:
        os.remove(seal_path())
    except Exception:
        pass


def local_payload() -> tuple[dict | None, str]:
    """(payload, state) for what is on this disk right now. No network."""
    blob = read_seal()
    if not blob:
        return None, STATE_MISSING
    payload = verify_blob(blob)
    if not payload:
        return None, STATE_TAMPERED
    if not binding_matches(payload):
        return None, STATE_TAMPERED
    if int(payload.get("ser") or 0) < _read_serial_floor():
        return None, STATE_TAMPERED
    return payload, STATE_SIGNED


# ── The grace window for shops that were already running ──────────────────────
def _activation_predates_cutover() -> bool:
    """Was this PC activated by a build that had no seal to fetch?

    No activation record at all is NOT a legacy install. That matters: wiping
    AppData is exactly how the delete trick is performed, and it takes
    activation.dat with it -- so the wiped machine lands in "no licence, fetch
    one" on its first launch rather than being handed the upgrade allowance.
    """
    try:
        from core.license_manager import _read_activation

        data = _read_activation() or {}
    except Exception:
        return False
    if not data:
        return False
    day = _as_date(data.get("date"))
    if day is None:
        # A record with no date was written by a build old enough to predate the
        # seal by definition.
        return True
    cutover = _as_date(SEAL_CUTOVER)
    return bool(cutover and day < cutover)


def in_legacy_grace() -> bool:
    """A shop that was running before the seal existed, still inside the window."""
    until = _as_date(LEGACY_GRACE_UNTIL)
    if until is None or _today() > until:
        return False
    return _activation_predates_cutover()


# ── The fresh install that never reached the server ───────────────────────────
def fresh_install_window() -> dict | None:
    """The starter licence for a PC activated here that has never had one.

    Returns ``{"activation_date", "expiry_date", "lapsed"}``, or None when this
    computer does not qualify. See FRESH_INSTALL_DAYS above for why each of
    these conditions is here; every one of them is load-bearing.

    Note what it does NOT do: it never extends a real expiry. The moment a
    signed licence exists, ``seal_state`` answers from the blob and never
    consults this at all -- and once one has EVER existed here, this refuses
    for the life of the activation record.
    """
    if seal_ever_stored():
        return None
    if _shop_already_trading():
        # Not a fresh install: this computer has bills on it. Whatever went
        # wrong with its licence, three free days is not the answer.
        return None
    try:
        from core.license_manager import _read_activation

        record = _read_activation() or {}
    except Exception:
        return None
    if not record:
        # No activation record: a wiped AppData, or a machine that never
        # finished setting up. Neither is a shop that has just been activated.
        return None
    # The FIRST activation this computer made, not the latest one: a
    # re-activation must not buy another window. Both places are read and the
    # earlier one wins, so deleting either file changes nothing.
    day = _as_date(record.get("first_date") or record.get("date"))
    marked = _as_date((_read_starter_marker() or {}).get("first"))
    if marked is not None and (day is None or marked < day):
        day = marked
    cutover = _as_date(SEAL_CUTOVER)
    if day is None or cutover is None or day < cutover:
        # Undated or pre-cutover records belong to the legacy path, which has
        # its own window and its own rules.
        return None
    if day > _today():
        # A clock set forward, or a record carried from another machine. Not a
        # licence to hand out days on.
        return None
    expiry = day + timedelta(days=FRESH_INSTALL_DAYS)
    _write_starter_marker(day)
    return {
        "activation_date": day.isoformat(),
        "expiry_date": expiry.isoformat(),
        "lapsed": _today() >= expiry,
    }


# ── Fetching ──────────────────────────────────────────────────────────────────
_FETCH_LOCK = threading.RLock()
_LAST_FETCH_AT = 0.0
_FETCH_EVERY_SEC = 60.0
_FETCH_THREAD: threading.Thread | None = None


def _binding_body() -> dict:
    from core.trial_activation import device_id, machine_id

    return {
        "machine_id": machine_id(),
        "device_id": device_id(),
        "hw_parts": binding_digests(),
    }


def _paired() -> bool:
    """Does this PC still hold an SC- key? Cheap, and no network."""
    try:
        from core.store_link import get_local_android_key

        return bool((get_local_android_key() or "").strip())
    except Exception:
        return False


def _fetch_seal_now(*, timeout: float) -> None:
    """The fetch itself. Runs on a worker thread; stores what it gets.

    Two ways in, tried in order, and the SECOND is the one this whole change
    exists for:

      1. With the store's own token, when this PC still has its SC- key.
      2. By hardware fingerprint, when it does not -- which is precisely the
         state a wiped AppData leaves behind. The server looks the machine up in
         its trial log and hands back the SAME licence it granted the first time.
         That is why deleting the file does not reset the date.
    """
    from core import server_api as api

    try:
        body = _binding_body()
    except Exception:
        return

    if _paired():
        # Only when there IS a key. store_token_for_active pairs over the
        # network when the cached token has lapsed, and an Offline shop that
        # never had a key would pay for that round trip to be told what it
        # already knows.
        try:
            token = (api.store_token_for_active() or "").strip()
        except Exception:
            token = ""
        if token:
            try:
                data = api.get_signed_license(token, body, timeout=timeout) or {}
                if store_seal(str(data.get("signed") or ""), fresh=True):
                    return
            except Exception:
                pass

    try:
        data = api.recover_signed_license(body, timeout=timeout) or {}
        store_seal(str(data.get("signed") or ""), fresh=True)
    except Exception:
        pass


def fetch_seal(
    *, timeout: float = 20.0, force: bool = False, wait: float | None = None
) -> dict | None:
    """Ask the server for this store's signed expiry. Returns the payload or None.

    ON A WORKER THREAD, with a bounded wait, because this is called from the
    LAUNCH path. A shop with no internet is exactly the shop that reaches here
    with no licence file, and a socket that takes its own sweet time to fail
    would hold the splash screen for as long as it liked. The worker keeps going
    after the wait expires and stores whatever it gets, so a slow answer is not
    a lost one -- the next licence read picks it up.

    ``wait=0`` starts the worker and returns immediately. That is for the
    OPPORTUNISTIC refresh -- the one taken while the server is already answering
    an Online licence read -- which improves the next offline launch and must
    never make this one slower.

    Rate-limited to once a minute per process: the licence status is polled by
    the desktop's status endpoint several times a second, and an unguarded call
    there would walk a shop into the server's own limiter and then tell it that
    it had been refused.
    """
    global _LAST_FETCH_AT, _FETCH_THREAD
    with _FETCH_LOCK:
        now = time.time()
        running = _FETCH_THREAD is not None and _FETCH_THREAD.is_alive()
        if not running:
            if not force and (now - _LAST_FETCH_AT) < _FETCH_EVERY_SEC:
                return None
            _LAST_FETCH_AT = now
            _FETCH_THREAD = threading.Thread(
                target=_fetch_seal_now,
                kwargs={"timeout": timeout},
                name="satpuda-licence-fetch",
                daemon=True,
            )
            _FETCH_THREAD.start()
        worker = _FETCH_THREAD

    hold = float(timeout) if wait is None else float(wait)
    if worker is not None and hold > 0:
        worker.join(max(0.5, hold))
    elif worker is not None:
        return None
    payload, state = local_payload()
    return payload if state == STATE_SIGNED else None


def ensure_seal(*, timeout: float = 8.0) -> tuple[dict | None, str]:
    """What this PC's licence is, fetching one if the local answer is not good.

    The short timeout is deliberate. This runs on the launch path, and a shop
    with no internet must not watch a splash screen while a socket times out --
    it is inside the grace window or it is not, and neither answer improves by
    waiting.
    """
    payload, state = local_payload()
    if state == STATE_SIGNED:
        if not payload_blocks(payload):
            return payload, state
        # THE LICENCE SAYS NO. Ask the server before turning the shop away.
        #
        # This is the one moment a refresh is worth a round trip: the vendor has
        # extended the date on the server and told the shopkeeper to connect the
        # internet, and without this the app would keep reading the stale blob
        # off its own disk and keep refusing. It is also the only way back for an
        # Offline shop whose trial has run out, because the Administrator screen
        # that could change the date is behind the block. Rate-limited to once a
        # minute like every other fetch, so a blocked shop does not hammer
        # anything while it waits.
        fresher = fetch_seal(timeout=timeout)
        return (fresher, STATE_SIGNED) if fresher else (payload, state)
    if not keys_configured():
        # No public key was compiled into this build, so nothing could ever
        # verify. Enforcing here would block every shop at once over a build
        # mistake. Report the state and let the caller fall back to the old
        # rules; test_the_build_carries_a_licence_key is what stops such a build
        # being shipped.
        return None, state
    if state == STATE_MISSING:
        window = fresh_install_window()
        if window and not window["lapsed"]:
            # Inside the starter window the till opens either way, so waiting
            # for the socket buys nothing. Start the fetch and walk away: the
            # shop this happens to is the shop with no internet, and it must not
            # watch a splash screen for the whole timeout every morning for
            # three days. A slow answer is not a lost one -- the worker stores
            # what it gets and the next licence read picks it up.
            fetch_seal(timeout=timeout, wait=0.0)
            return None, state
    fetched = fetch_seal(timeout=timeout)
    if fetched:
        return fetched, STATE_SIGNED
    return None, state


# ── What the rest of the app asks ─────────────────────────────────────────────
def seal_state(*, fetch: bool = True, timeout: float = 8.0) -> dict:
    """The licence, and whether it blocks. The one function callers need.

    ``blocked`` is why this is not simply a date:

      * ``signed``   -- the blob decides, exactly as the server wrote it.
      * ``legacy``   -- a shop that predates the seal, inside the grace window.
        The caller applies the OLD rules; nothing here blocks it.
      * ``missing`` / ``tampered`` -- blocked, and the reason is not "expired".
        The shop is told to connect the internet once. It is deliberately NOT an
        expiry: expiry in Offline mode deletes activation.dat to force the
        vendor's re-activation, and doing that to a shop whose file merely went
        missing would destroy the one record that says it was ever activated.
    """
    payload, state = (ensure_seal(timeout=timeout) if fetch else local_payload())
    if state == STATE_SIGNED and payload:
        return {
            "state": STATE_SIGNED,
            "blocked": bool(payload_blocks(payload)),
            "reason": payload_block_reason(payload),
            "expiry_date": str(payload.get("exp") or ""),
            "activation_date": str(payload.get("act") or ""),
            "enabled": bool(payload.get("een")),
            "apply_expiry_check": bool(payload.get("aec", True)),
            "is_active": bool(payload.get("act_ok", True)),
            "serial": int(payload.get("ser") or 0),
            "message": "",
            "payload": payload,
        }
    if in_legacy_grace():
        return {
            "state": STATE_LEGACY,
            "blocked": False,
            "reason": "",
            "expiry_date": "",
            "activation_date": "",
            "enabled": False,
            "apply_expiry_check": True,
            "is_active": True,
            "serial": 0,
            "message": NEEDS_INTERNET_MESSAGE,
            "payload": None,
        }
    # A fresh install whose sign-up never reached the server. It opens on its
    # starter window and then EXPIRES -- reason "expired", not "needs_internet",
    # because the shop is out of time rather than out of a file. A tampered blob
    # is never a fresh install.
    if state == STATE_MISSING:
        window = fresh_install_window()
        if window:
            lapsed = bool(window["lapsed"])
            return {
                "state": STATE_FRESH,
                "blocked": lapsed,
                "reason": "expired" if lapsed else "",
                "expiry_date": window["expiry_date"],
                "activation_date": window["activation_date"],
                "enabled": True,
                "apply_expiry_check": True,
                "is_active": True,
                "serial": 0,
                "message": (
                    FRESH_INSTALL_LAPSED_MESSAGE.format(days=FRESH_INSTALL_DAYS)
                    if lapsed
                    else FRESH_INSTALL_MESSAGE.format(
                        days=FRESH_INSTALL_DAYS, until=window["expiry_date"]
                    )
                ),
                "payload": None,
            }
    if not keys_configured():
        # See ensure_seal: an unkeyed build must not block the fleet.
        return {
            "state": STATE_LEGACY,
            "blocked": False,
            "reason": "",
            "expiry_date": "",
            "activation_date": "",
            "enabled": False,
            "apply_expiry_check": True,
            "is_active": True,
            "serial": 0,
            "message": "",
            "payload": None,
        }
    return {
        "state": state,
        "blocked": True,
        "reason": "needs_internet",
        "expiry_date": "",
        "activation_date": "",
        "enabled": False,
        "apply_expiry_check": True,
        "is_active": True,
        "serial": 0,
        "message": TAMPERED_MESSAGE if state == STATE_TAMPERED else NEEDS_INTERNET_MESSAGE,
        "payload": None,
    }


def payload_blocks(payload: dict) -> bool:
    """Does this signed licence deny access today?"""
    if not isinstance(payload, dict):
        return True
    if payload.get("act_ok") is False:
        return True
    if not bool(payload.get("aec", True)):
        return False
    if not bool(payload.get("een")):
        return False
    expiry = _as_date(payload.get("exp"))
    if expiry is None:
        return False
    return _today() >= expiry


def payload_block_reason(payload: dict) -> str:
    if not isinstance(payload, dict):
        return "needs_internet"
    if payload.get("act_ok") is False:
        return "access_disabled"
    return "expired" if payload_blocks(payload) else ""


def issued_at(payload: dict) -> str:
    try:
        return datetime.fromtimestamp(int(payload.get("iat") or 0), timezone.utc).isoformat()
    except Exception:
        return ""
