from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def make_entry(
    entry_id: str,
    screens: list[str],
    keywords: list[str],
    en: str,
    mr: str,
    hi: str,
    triggers: list[str] | None = None,
) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "id": entry_id,
        "screens": screens,
        "keywords": keywords,
        "responses": {"en": en, "mr": mr, "hi": hi},
    }
    if triggers:
        entry["triggers"] = triggers
    return entry


def build_entries() -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = [
        make_entry(
            "sales_add_customer",
            ["sales_billing"],
            ["add customer", "customer", "ग्राहक", "ग्राहक जोडा", "कस्टमर जोड़ें"],
            "1. Open Sales Billing screen.\n2. Type customer name and mobile in the customer fields.\n3. Press F5 to save the bill when entry is complete.",
            "1. Sales Billing स्क्रीन उघडा.\n2. ग्राहकाचे नाव आणि मोबाईल ग्राहक फील्डमध्ये भरा.\n3. बिल पूर्ण झाल्यावर F5 दाबून सेव्ह करा.",
            "1. Sales Billing स्क्रीन खोलें.\n2. ग्राहक का नाम और मोबाइल ग्राहक फ़ील्ड में भरें.\n3. एंट्री पूरी होने पर F5 दबाकर बिल सेव करें.",
            ["new customer", "customer details"],
        ),
        make_entry(
            "sales_add_medicine_row",
            ["sales_billing"],
            ["add medicine", "medicine row", "औषध जोडा", "दवा जोड़ें", "मेडिसिन"],
            "1. In Sales Billing, search medicine in the item field.\n2. Select the medicine to add a filled row in the bill table.\n3. Update quantity and continue billing.",
            "1. Sales Billing मध्ये आयटम फील्डमध्ये औषध शोधा.\n2. औषध निवडताच बिल टेबलमध्ये भरलेली ओळ तयार होते.\n3. प्रमाण बदला आणि बिलिंग सुरू ठेवा.",
            "1. Sales Billing में आइटम फ़ील्ड में दवा खोजें.\n2. दवा चुनते ही बिल टेबल में भरी हुई पंक्ति जुड़ती है.\n3. मात्रा बदलें और बिलिंग जारी रखें.",
            ["medicine not adding", "row not filled"],
        ),
        make_entry(
            "sales_stock_reduce_on_save",
            ["sales_billing"],
            ["stock reduce", "less stock", "स्टॉक कमी", "स्टॉक घटेगा", "विक्री स्टॉक"],
            "1. Add medicines and quantities in Sales Billing.\n2. Confirm totals and payment details.\n3. Press F5 to save; stock is reduced after successful save.",
            "1. Sales Billing मध्ये औषधे आणि प्रमाण भरा.\n2. एकूण रक्कम आणि पेमेंट तपासा.\n3. F5 ने सेव्ह केल्यावर स्टॉक कमी होतो.",
            "1. Sales Billing में दवा और मात्रा भरें.\n2. कुल राशि और पेमेंट जांचें.\n3. F5 से सेव करने के बाद स्टॉक कम होता है.",
        ),
        make_entry(
            "sales_new_tab",
            ["sales_billing"],
            ["new tab", "new bill", "नवीन टॅब", "नया टैब", "नवीन बिल"],
            "1. Complete or hold the current sale.\n2. Click New Tab in Sales Billing.\n3. Start the next customer bill in the new tab.",
            "1. चालू विक्री पूर्ण करा किंवा होल्ड करा.\n2. Sales Billing मध्ये New Tab क्लिक करा.\n3. पुढच्या ग्राहकाचे बिल नवीन टॅबमध्ये सुरू करा.",
            "1. चालू बिक्री पूरी करें या होल्ड करें.\n2. Sales Billing में New Tab पर क्लिक करें.\n3. अगले ग्राहक का बिल नए टैब में शुरू करें.",
        ),
        make_entry(
            "sales_counter_sale",
            ["sales_billing"],
            ["counter sale", "walk in", "काउंटर सेल", "काउंटर विक्री", "रोख ग्राहक"],
            "1. Keep customer fields blank for walk-in sale.\n2. Add medicines and payment mode.\n3. Press F5 to save the counter sale quickly.",
            "1. वॉक-इन विक्रीसाठी ग्राहक फील्ड रिकामे ठेवा.\n2. औषधे आणि पेमेंट मोड भरा.\n3. काउंटर विक्रीसाठी F5 दाबून लगेच सेव्ह करा.",
            "1. वॉक-इन बिक्री के लिए ग्राहक फ़ील्ड खाली रखें.\n2. दवा और पेमेंट मोड भरें.\n3. काउंटर बिक्री के लिए F5 दबाकर तुरंत सेव करें.",
        ),
        make_entry(
            "sales_add_no_stock",
            ["sales_billing"],
            ["no stock", "add without stock", "स्टॉक नाही", "बिना स्टॉक", "स्टॉक नाही तरी"],
            "1. Search the medicine in Sales Billing.\n2. If stock is zero, add only if your policy allows no-stock billing.\n3. Verify quantity carefully before pressing F5.",
            "1. Sales Billing मध्ये औषध शोधा.\n2. स्टॉक शून्य असल्यास दुकानाच्या नियमाप्रमाणेच ओळ जोडा.\n3. F5 दाबण्यापूर्वी प्रमाण नीट तपासा.",
            "1. Sales Billing में दवा खोजें.\n2. स्टॉक शून्य हो तो दुकान नीति अनुसार ही बिना स्टॉक एंट्री करें.\n3. F5 दबाने से पहले मात्रा ध्यान से जांचें.",
        ),
        make_entry(
            "purchase_add_supplier",
            ["purchase"],
            ["add supplier", "supplier", "पुरवठादार जोडा", "सप्लायर जोड़ें", "supplier name"],
            "1. Open Purchase screen.\n2. Enter supplier details directly in supplier fields with no popup.\n3. Press F5 to save the purchase bill.",
            "1. Purchase स्क्रीन उघडा.\n2. पुरवठादार तपशील थेट फील्डमध्ये भरा, वेगळा पॉपअप येत नाही.\n3. खरेदी बिल सेव्ह करण्यासाठी F5 दाबा.",
            "1. Purchase स्क्रीन खोलें.\n2. सप्लायर विवरण सीधे फ़ील्ड में भरें, कोई पॉपअप नहीं आता.\n3. खरीद बिल सेव करने के लिए F5 दबाएँ.",
            ["supplier popup", "no popup supplier"],
        ),
        make_entry(
            "purchase_add_medicine_row",
            ["purchase"],
            ["purchase medicine", "add medicine", "औषध जोडा", "दवा जोड़ें", "खरेदी औषध"],
            "1. In Purchase, type or scan medicine in the item field.\n2. Select medicine to add a filled row in the table.\n3. Enter batch, qty, rate and continue.",
            "1. Purchase मध्ये आयटम फील्डमध्ये औषध टाइप करा किंवा स्कॅन करा.\n2. औषध निवडल्यावर टेबलमध्ये भरलेली ओळ तयार होते.\n3. बॅच, प्रमाण, दर भरून पुढे जा.",
            "1. Purchase में आइटम फ़ील्ड में दवा टाइप या स्कैन करें.\n2. दवा चुनते ही टेबल में भरी हुई पंक्ति जुड़ती है.\n3. बैच, मात्रा, रेट भरकर आगे बढ़ें.",
        ),
        make_entry(
            "purchase_supplier_save_timing",
            ["purchase"],
            ["save timing", "when supplier saved", "कधी सेव्ह", "कब सेव", "supplier save"],
            "1. Fill supplier and bill details on Purchase screen.\n2. Add all medicine rows and totals.\n3. Press F5; supplier and bill data save together.",
            "1. Purchase स्क्रीनवर पुरवठादार आणि बिल तपशील भरा.\n2. सर्व औषध ओळी आणि एकूण रक्कम भरा.\n3. F5 दाबल्यावर पुरवठादार व बिल डेटा एकत्र सेव्ह होतो.",
            "1. Purchase स्क्रीन पर सप्लायर और बिल विवरण भरें.\n2. सभी दवा पंक्तियां और कुल राशि भरें.\n3. F5 दबाने पर सप्लायर और बिल डेटा साथ में सेव होता है.",
        ),
        make_entry(
            "purchase_stock_increase_on_save",
            ["purchase"],
            ["stock increase", "purchase stock", "स्टॉक वाढ", "स्टॉक बढ़ेगा", "खरेदी स्टॉक"],
            "1. Enter all purchase lines with quantity.\n2. Verify tax and net amount.\n3. Press F5 to save; stock increases after save.",
            "1. सर्व खरेदी ओळी प्रमाणासह भरा.\n2. कर आणि नेट रक्कम तपासा.\n3. F5 ने सेव्ह केल्यावर स्टॉक वाढतो.",
            "1. सभी खरीद पंक्तियां मात्रा सहित भरें.\n2. टैक्स और नेट राशि जांचें.\n3. F5 से सेव करने के बाद स्टॉक बढ़ता है.",
        ),
        make_entry(
            "purchase_new_tab",
            ["purchase"],
            ["new tab purchase", "नवीन टॅब", "नया टैब", "next purchase", "नवी खरेदी"],
            "1. Finish current purchase entry.\n2. Click New Tab on Purchase screen.\n3. Start next supplier bill in the new tab.",
            "1. चालू खरेदी एंट्री पूर्ण करा.\n2. Purchase स्क्रीनवर New Tab क्लिक करा.\n3. पुढचे पुरवठादार बिल नवीन टॅबमध्ये सुरू करा.",
            "1. चालू खरीद एंट्री पूरी करें.\n2. Purchase स्क्रीन पर New Tab क्लिक करें.\n3. अगला सप्लायर बिल नए टैब में शुरू करें.",
        ),
        make_entry(
            "inventory_filter_live",
            ["inventory"],
            ["live filter", "filter instantly", "लाईव्ह फिल्टर", "लाइव फ़िल्टर", "apply filter"],
            "1. Open Inventory screen.\n2. Type text in search or change filter fields.\n3. Results update live automatically, no Apply Filter button is needed.",
            "1. Inventory स्क्रीन उघडा.\n2. शोध मजकूर टाका किंवा फिल्टर बदला.\n3. निकाल लाईव्ह बदलतात, Apply Filter बटन लागत नाही.",
            "1. Inventory स्क्रीन खोलें.\n2. खोज टेक्स्ट लिखें या फ़िल्टर बदलें.\n3. परिणाम लाइव बदलते हैं, Apply Filter बटन की जरूरत नहीं है.",
            ["inventory apply filter", "no apply"],
        ),
        make_entry(
            "inventory_edit_medicine",
            ["inventory"],
            ["edit medicine", "modify item", "औषध संपादन", "दवा संपादित", "एडिट"],
            "1. Find the medicine in Inventory.\n2. Open edit action for that row.\n3. Update fields and save changes.",
            "1. Inventory मध्ये औषध शोधा.\n2. त्या ओळीचा edit पर्याय उघडा.\n3. फील्ड बदलून सेव्ह करा.",
            "1. Inventory में दवा खोजें.\n2. उस पंक्ति का edit विकल्प खोलें.\n3. फ़ील्ड बदलकर सेव करें.",
        ),
        make_entry(
            "inventory_view_details",
            ["inventory"],
            ["view details", "medicine details", "तपशील पहा", "विवरण देखें", "details"],
            "1. Select medicine row in Inventory.\n2. Click View Details.\n3. Check batch, stock, rate and expiry information.",
            "1. Inventory मध्ये औषधाची ओळ निवडा.\n2. View Details क्लिक करा.\n3. बॅच, स्टॉक, दर आणि expiry माहिती तपासा.",
            "1. Inventory में दवा की पंक्ति चुनें.\n2. View Details क्लिक करें.\n3. बैच, स्टॉक, रेट और एक्सपायरी जानकारी देखें.",
        ),
        make_entry(
            "inventory_reorder_action",
            ["inventory", "settings_reorder"],
            ["reorder", "low stock order", "रीऑर्डर", "रिऑर्डर", "कमी स्टॉक"],
            "1. Open Inventory and identify low stock items.\n2. Use reorder action to send item to reorder workflow.\n3. Place supplier order from Reorder settings.",
            "1. Inventory मध्ये कमी स्टॉक आयटम ओळखा.\n2. Reorder action वापरून आयटम reorder workflow मध्ये पाठवा.\n3. Reorder सेटिंगमधून पुरवठादार ऑर्डर करा.",
            "1. Inventory में कम स्टॉक आइटम पहचानें.\n2. Reorder action से आइटम reorder workflow में भेजें.\n3. Reorder सेटिंग से सप्लायर ऑर्डर करें.",
        ),
        make_entry(
            "inventory_export",
            ["inventory"],
            ["export inventory", "inventory report", "निर्यात", "एक्सपोर्ट", "स्टॉक रिपोर्ट"],
            "1. Apply the needed live filters in Inventory.\n2. Click Export.\n3. Save the generated stock file.",
            "1. Inventory मध्ये आवश्यक लाईव्ह फिल्टर लावा.\n2. Export क्लिक करा.\n3. तयार झालेली स्टॉक फाइल सेव्ह करा.",
            "1. Inventory में जरूरत के लाइव फ़िल्टर लगाएँ.\n2. Export क्लिक करें.\n3. बनी हुई स्टॉक फ़ाइल सेव करें.",
        ),
        make_entry(
            "inventory_clear_filters",
            ["inventory"],
            ["clear filters", "reset filter", "फिल्टर काढा", "फ़िल्टर हटाएं", "reset"],
            "1. Open Inventory filters section.\n2. Click Clear Filters or reset fields.\n3. Full list reloads live.",
            "1. Inventory फिल्टर विभाग उघडा.\n2. Clear Filters क्लिक करा किंवा फील्ड रिकामे करा.\n3. पूर्ण यादी लाईव्ह परत दिसते.",
            "1. Inventory फ़िल्टर सेक्शन खोलें.\n2. Clear Filters क्लिक करें या फ़ील्ड खाली करें.\n3. पूरी सूची लाइव वापस दिखती है.",
        ),
        make_entry(
            "inventory_delete_zero_stock",
            ["inventory"],
            ["delete zero stock", "remove zero", "शून्य स्टॉक हटवा", "जीरो स्टॉक हटाएं", "zero qty"],
            "1. Filter Inventory for zero stock items.\n2. Select delete zero stock action.\n3. Confirm removal carefully.",
            "1. Inventory मध्ये शून्य स्टॉक आयटम फिल्टर करा.\n2. delete zero stock action निवडा.\n3. खात्री करून काढून टाका.",
            "1. Inventory में शून्य स्टॉक आइटम फ़िल्टर करें.\n2. delete zero stock action चुनें.\n3. ध्यान से पुष्टि करके हटाएँ.",
        ),
        make_entry(
            "sales_history_apply_filter_dates",
            ["sales_history"],
            ["sales history filter", "date filter", "तारीख फिल्टर", "दिनांक फ़िल्टर", "apply filter"],
            "1. Open Sales History.\n2. Select from and to dates.\n3. Click Apply Filter to load matching bills.",
            "1. Sales History उघडा.\n2. पासून आणि पर्यंत तारीख निवडा.\n3. Apply Filter क्लिक करून जुळणारी बिले पहा.",
            "1. Sales History खोलें.\n2. शुरू और अंत तारीख चुनें.\n3. Apply Filter क्लिक करके मिलते बिल देखें.",
        ),
        make_entry(
            "sales_history_edit_bill",
            ["sales_history"],
            ["edit bill", "modify sale bill", "बिल संपादन", "बिल संपादित", "edit sales"],
            "1. Open Sales History and filter dates if needed.\n2. Select the bill and click Edit.\n3. Save the corrected bill.",
            "1. Sales History उघडा आणि गरजेनुसार तारीख फिल्टर लावा.\n2. बिल निवडून Edit क्लिक करा.\n3. दुरुस्त बिल सेव्ह करा.",
            "1. Sales History खोलें और जरूरत हो तो तारीख फ़िल्टर लगाएँ.\n2. बिल चुनकर Edit क्लिक करें.\n3. सुधरा हुआ बिल सेव करें.",
        ),
        make_entry(
            "sales_history_view_details",
            ["sales_history"],
            ["view sale details", "bill details", "तपशील", "विवरण", "history details"],
            "1. Select a bill in Sales History.\n2. Click View Details.\n3. Verify customer, items, and totals.",
            "1. Sales History मध्ये बिल निवडा.\n2. View Details क्लिक करा.\n3. ग्राहक, आयटम आणि एकूण तपासा.",
            "1. Sales History में बिल चुनें.\n2. View Details क्लिक करें.\n3. ग्राहक, आइटम और कुल राशि जांचें.",
        ),
        make_entry(
            "sales_history_export_filtered",
            ["sales_history"],
            ["export filtered", "filtered sales export", "फिल्टर एक्सपोर्ट", "फ़िल्टर एक्सपोर्ट", "history export"],
            "1. Set date and other filters in Sales History.\n2. Click Apply Filter.\n3. Click Export Filtered to download report.",
            "1. Sales History मध्ये तारीख आणि इतर फिल्टर लावा.\n2. Apply Filter क्लिक करा.\n3. Export Filtered करून रिपोर्ट घ्या.",
            "1. Sales History में तारीख और अन्य फ़िल्टर लगाएँ.\n2. Apply Filter क्लिक करें.\n3. Export Filtered से रिपोर्ट डाउनलोड करें.",
        ),
        make_entry(
            "sales_history_print_all",
            ["sales_history"],
            ["print all", "all bills print", "सर्व प्रिंट", "सभी प्रिंट", "history print"],
            "1. Open Sales History.\n2. Keep filters cleared or set as needed.\n3. Click Print All to print visible records.",
            "1. Sales History उघडा.\n2. फिल्टर काढा किंवा गरजेनुसार ठेवा.\n3. Print All क्लिक करून दिसणारे रेकॉर्ड प्रिंट करा.",
            "1. Sales History खोलें.\n2. फ़िल्टर हटाएँ या जरूरत अनुसार रखें.\n3. Print All क्लिक करके दिख रहे रिकॉर्ड प्रिंट करें.",
        ),
        make_entry(
            "sales_history_clear_filter",
            ["sales_history"],
            ["clear filter", "reset sales history", "फिल्टर साफ", "फ़िल्टर हटाएं", "clear date"],
            "1. In Sales History, open filter controls.\n2. Click Clear Filter.\n3. Full unfiltered bill list appears.",
            "1. Sales History मध्ये फिल्टर विभाग उघडा.\n2. Clear Filter क्लिक करा.\n3. पूर्ण अनफिल्टर्ड बिल यादी दिसेल.",
            "1. Sales History में फ़िल्टर कंट्रोल खोलें.\n2. Clear Filter क्लिक करें.\n3. पूरी बिना फ़िल्टर बिल सूची दिखेगी.",
        ),
        make_entry(
            "purchase_history_edit",
            ["purchase_history"],
            ["edit purchase", "modify purchase bill", "खरेदी संपादन", "खरीद संपादित", "edit"],
            "1. Open Purchase History.\n2. Select the bill and click Edit.\n3. Update values and save.",
            "1. Purchase History उघडा.\n2. बिल निवडून Edit क्लिक करा.\n3. मूल्ये बदलून सेव्ह करा.",
            "1. Purchase History खोलें.\n2. बिल चुनकर Edit क्लिक करें.\n3. मान बदलकर सेव करें.",
        ),
        make_entry(
            "purchase_history_apply_filter",
            ["purchase_history"],
            ["purchase filter", "date wise purchase", "फिल्टर", "फ़िल्टर", "apply filter"],
            "1. Open Purchase History.\n2. Select date range and supplier if needed.\n3. Click Apply Filter to show matching entries.",
            "1. Purchase History उघडा.\n2. तारीख रेंज आणि पुरवठादार निवडा.\n3. Apply Filter क्लिक करून जुळणाऱ्या नोंदी पहा.",
            "1. Purchase History खोलें.\n2. तारीख रेंज और सप्लायर चुनें.\n3. Apply Filter क्लिक करके मिलती एंट्री देखें.",
        ),
        make_entry(
            "purchase_history_export_register",
            ["purchase_history"],
            ["export register", "purchase register", "रजिस्टर एक्सपोर्ट", "रजिस्टर निर्यात", "खरेदी रजिस्टर"],
            "1. Apply desired filters in Purchase History.\n2. Click Export Register.\n3. Save the generated purchase register file.",
            "1. Purchase History मध्ये आवश्यक फिल्टर लावा.\n2. Export Register क्लिक करा.\n3. तयार झालेली खरेदी रजिस्टर फाइल सेव्ह करा.",
            "1. Purchase History में जरूरी फ़िल्टर लगाएँ.\n2. Export Register क्लिक करें.\n3. बनी हुई खरीद रजिस्टर फ़ाइल सेव करें.",
        ),
        make_entry(
            "purchase_history_paid_at_entry",
            ["purchase_history", "purchase"],
            ["paid at entry", "payment at purchase", "paid", "पेमेंट", "भरलेले"],
            "1. Open Purchase or Purchase History entry.\n2. Fill paid amount at the time of bill entry.\n3. Save to update dues and ledger.",
            "1. Purchase किंवा Purchase History एंट्री उघडा.\n2. बिल एंट्रीवेळी paid amount भरा.\n3. सेव्ह केल्यावर dues आणि ledger अपडेट होतात.",
            "1. Purchase या Purchase History एंट्री खोलें.\n2. बिल एंट्री के समय paid amount भरें.\n3. सेव करने पर dues और ledger अपडेट होते हैं.",
        ),
        make_entry(
            "purchase_history_gst_export",
            ["purchase_history"],
            ["gst export", "purchase gst", "जीएसटी एक्सपोर्ट", "GST निर्यात", "tax export"],
            "1. Open Purchase History with required dates.\n2. Apply Filter.\n3. Click GST Export to download GST-ready data.",
            "1. Purchase History मध्ये आवश्यक तारीख उघडा.\n2. Apply Filter क्लिक करा.\n3. GST Export करून GST साठी डेटा घ्या.",
            "1. Purchase History में जरूरी तारीख चुनें.\n2. Apply Filter क्लिक करें.\n3. GST Export करके GST के लिए डेटा डाउनलोड करें.",
        ),
        make_entry(
            "returns_sales",
            ["returns_sales"],
            ["sales return", "return sale", "विक्री परत", "बिक्री वापसी", "customer return"],
            "1. Open Sales Return screen.\n2. Search original sale bill and select items to return.\n3. Save return entry to adjust stock and amount.",
            "1. Sales Return स्क्रीन उघडा.\n2. मूळ विक्री बिल शोधून परत आयटम निवडा.\n3. सेव्ह केल्यावर स्टॉक आणि रक्कम समायोजित होते.",
            "1. Sales Return स्क्रीन खोलें.\n2. मूल बिक्री बिल खोजकर वापसी आइटम चुनें.\n3. सेव करने पर स्टॉक और राशि समायोजित होती है.",
        ),
        make_entry(
            "returns_purchase",
            ["returns_purchase"],
            ["purchase return", "return to supplier", "खरेदी परत", "खरीद वापसी", "supplier return"],
            "1. Open Purchase Return screen.\n2. Select supplier bill and return quantities.\n3. Save return to reduce stock and supplier payable.",
            "1. Purchase Return स्क्रीन उघडा.\n2. पुरवठादार बिल निवडून परत प्रमाण भरा.\n3. सेव्ह केल्यावर स्टॉक आणि देय रक्कम कमी होते.",
            "1. Purchase Return स्क्रीन खोलें.\n2. सप्लायर बिल चुनकर वापसी मात्रा भरें.\n3. सेव करने पर स्टॉक और सप्लायर देय राशि घटती है.",
        ),
        make_entry(
            "returns_disposal",
            ["returns_disposal"],
            ["disposal return", "expired disposal", "डिस्पोजल", "नष्ट नोंद", "expired remove"],
            "1. Open Disposal Return screen.\n2. Select damaged or expired medicines.\n3. Save disposal entry for stock deduction and records.",
            "1. Disposal Return स्क्रीन उघडा.\n2. खराब किंवा कालबाह्य औषधे निवडा.\n3. स्टॉक कपात आणि नोंदीसाठी disposal एंट्री सेव्ह करा.",
            "1. Disposal Return स्क्रीन खोलें.\n2. खराब या एक्सपायर्ड दवाएं चुनें.\n3. स्टॉक कटौती और रिकॉर्ड के लिए disposal एंट्री सेव करें.",
        ),
        make_entry(
            "reorder_mark_received",
            ["settings_reorder", "purchase"],
            ["mark received", "receive order", "माल आला", "प्राप्त करें", "received"],
            "1. Open Purchase first and create the actual inward entry if stock is coming in.\n2. In Reorder settings, use Mark Received only to close reorder tracking.\n3. Mark Received does not add stock by itself.",
            "1. स्टॉक येत असल्यास आधी Purchase उघडून प्रत्यक्ष inward एंट्री करा.\n2. Reorder सेटिंगमध्ये Mark Received फक्त ट्रॅकिंग बंद करण्यासाठी वापरा.\n3. Mark Received ने एकट्याने स्टॉक वाढत नाही.",
            "1. स्टॉक आने पर पहले Purchase खोलकर वास्तविक inward एंट्री करें.\n2. Reorder सेटिंग में Mark Received सिर्फ ट्रैकिंग बंद करने के लिए है.\n3. Mark Received से अपने आप स्टॉक नहीं बढ़ता.",
            ["received stock not added", "mark received stock"],
        ),
        make_entry(
            "reorder_place_order",
            ["settings_reorder"],
            ["place order", "create reorder order", "ऑर्डर करा", "ऑर्डर करें", "reorder order"],
            "1. Open Settings Reorder and review low stock lines.\n2. Select required items and supplier.\n3. Click Place Order to create reorder order.",
            "1. Settings Reorder उघडा आणि कमी स्टॉक ओळी तपासा.\n2. आवश्यक आयटम आणि पुरवठादार निवडा.\n3. Place Order क्लिक करून ऑर्डर तयार करा.",
            "1. Settings Reorder खोलें और कम स्टॉक पंक्तियां देखें.\n2. जरूरी आइटम और सप्लायर चुनें.\n3. Place Order क्लिक करके ऑर्डर बनाएं.",
        ),
        make_entry(
            "reorder_load_by_supplier",
            ["settings_reorder"],
            ["load by supplier", "supplier wise reorder", "पुरवठादारनुसार", "सप्लायर अनुसार", "load supplier"],
            "1. Open Reorder settings.\n2. Choose supplier in filter.\n3. Click Load by Supplier to view pending lines for that supplier.",
            "1. Reorder सेटिंग उघडा.\n2. फिल्टरमध्ये पुरवठादार निवडा.\n3. Load by Supplier क्लिक करून त्या पुरवठादाराच्या ओळी पहा.",
            "1. Reorder सेटिंग खोलें.\n2. फ़िल्टर में सप्लायर चुनें.\n3. Load by Supplier क्लिक करके उस सप्लायर की पेंडिंग पंक्तियां देखें.",
        ),
        make_entry(
            "reorder_save_draft",
            ["settings_reorder"],
            ["save draft", "draft reorder", "ड्राफ्ट सेव्ह", "ड्राफ्ट सेव", "temporary save"],
            "1. Prepare reorder quantities and supplier mapping.\n2. Click Save Draft.\n3. Resume and place order later.",
            "1. reorder प्रमाण आणि पुरवठादार मॅपिंग तयार करा.\n2. Save Draft क्लिक करा.\n3. नंतर परत उघडून ऑर्डर पूर्ण करा.",
            "1. reorder मात्रा और सप्लायर मैपिंग तैयार करें.\n2. Save Draft क्लिक करें.\n3. बाद में खोलकर ऑर्डर पूरा करें.",
        ),
        make_entry(
            "reorder_defaults",
            ["settings_reorder"],
            ["reorder defaults", "default values", "डीफॉल्ट सेटिंग", "डिफ़ॉल्ट सेटिंग", "auto qty"],
            "1. Open Reorder defaults in settings.\n2. Set min/max or suggested order rules.\n3. Save defaults for future reorder calculations.",
            "1. सेटिंगमध्ये Reorder defaults उघडा.\n2. min/max किंवा सुचवलेले ऑर्डर नियम सेट करा.\n3. पुढील reorder गणनेसाठी defaults सेव्ह करा.",
            "1. सेटिंग में Reorder defaults खोलें.\n2. min/max या सुझाए गए ऑर्डर नियम सेट करें.\n3. आगे की reorder गणना के लिए defaults सेव करें.",
        ),
        make_entry(
            "settings_payment_supplier",
            ["settings_payment"],
            ["supplier payment", "pay supplier", "पुरवठादार पेमेंट", "सप्लायर भुगतान", "supplier due"],
            "1. Open Settings Payment and choose Supplier tab.\n2. Select supplier and enter paid amount.\n3. Save payment to update dues and ledger.",
            "1. Settings Payment उघडून Supplier टॅब निवडा.\n2. पुरवठादार निवडून paid amount भरा.\n3. सेव्ह केल्यावर dues आणि ledger अपडेट होतात.",
            "1. Settings Payment खोलकर Supplier टैब चुनें.\n2. सप्लायर चुनकर paid amount भरें.\n3. सेव करने पर dues और ledger अपडेट होते हैं.",
        ),
        make_entry(
            "settings_payment_customer",
            ["settings_payment"],
            ["customer payment", "customer due", "ग्राहक पेमेंट", "ग्राहक भुगतान", "receive payment"],
            "1. Open Settings Payment and choose Customer tab.\n2. Select customer and enter received amount.\n3. Save to reduce customer outstanding balance.",
            "1. Settings Payment मध्ये Customer टॅब निवडा.\n2. ग्राहक निवडून मिळालेली रक्कम भरा.\n3. सेव्ह केल्यावर बाकी रक्कम कमी होते.",
            "1. Settings Payment में Customer टैब चुनें.\n2. ग्राहक चुनकर प्राप्त राशि भरें.\n3. सेव करने पर बकाया राशि कम होती है.",
        ),
        make_entry(
            "settings_ledger",
            ["settings_ledger"],
            ["ledger", "khata", "लेजर", "खाते", "हिशेब"],
            "1. Open Settings Ledger.\n2. Filter by party and date range.\n3. View running balance and export if needed.",
            "1. Settings Ledger उघडा.\n2. पार्टी आणि तारीख रेंजने फिल्टर करा.\n3. चालू शिल्लक पहा आणि गरज असल्यास एक्सपोर्ट करा.",
            "1. Settings Ledger खोलें.\n2. पार्टी और तारीख रेंज से फ़िल्टर करें.\n3. चालू बैलेंस देखें और जरूरत हो तो एक्सपोर्ट करें.",
        ),
        make_entry(
            "settings_alerts_remove_all_expired",
            ["settings_alerts"],
            ["remove all expired", "clear expired", "कालबाह्य काढा", "एक्सपायर्ड हटाएं", "expired alert"],
            "1. Open Settings Alerts.\n2. Use Remove All Expired option.\n3. Confirm action to clean expired alerts list.",
            "1. Settings Alerts उघडा.\n2. Remove All Expired पर्याय वापरा.\n3. पुष्टी देऊन expired alerts सूची साफ करा.",
            "1. Settings Alerts खोलें.\n2. Remove All Expired विकल्प उपयोग करें.\n3. पुष्टि करके expired alerts सूची साफ करें.",
        ),
        make_entry(
            "settings_alerts_reorder",
            ["settings_alerts", "settings_reorder"],
            ["reorder alert", "low stock alert", "रीऑर्डर अलर्ट", "रिऑर्डर अलर्ट", "low stock"],
            "1. Open Settings Alerts.\n2. Review low stock reorder alerts.\n3. Open related reorder action or dismiss alert.",
            "1. Settings Alerts उघडा.\n2. कमी स्टॉक reorder alerts तपासा.\n3. संबंधित reorder action उघडा किंवा alert बंद करा.",
            "1. Settings Alerts खोलें.\n2. कम स्टॉक reorder alerts देखें.\n3. संबंधित reorder action खोलें या alert बंद करें.",
        ),
        make_entry(
            "settings_alerts_refresh",
            ["settings_alerts"],
            ["refresh alerts", "reload alerts", "अलर्ट रिफ्रेश", "अलर्ट रिफ्रेश", "refresh"],
            "1. Open Settings Alerts.\n2. Click Refresh.\n3. Latest alert list loads from current data.",
            "1. Settings Alerts उघडा.\n2. Refresh क्लिक करा.\n3. चालू डेटानुसार नवीन alert सूची दिसेल.",
            "1. Settings Alerts खोलें.\n2. Refresh क्लिक करें.\n3. वर्तमान डेटा के अनुसार नई alert सूची दिखेगी.",
        ),
        make_entry(
            "settings_alerts_return",
            ["settings_alerts"],
            ["return alert", "return reminders", "रिटर्न अलर्ट", "वापसी अलर्ट", "returns alert"],
            "1. Open Settings Alerts.\n2. Check return-related reminders.\n3. Open return screen from alert or mark handled.",
            "1. Settings Alerts उघडा.\n2. return संबंधी स्मरणपत्र तपासा.\n3. alert मधून return स्क्रीन उघडा किंवा handled मार्क करा.",
            "1. Settings Alerts खोलें.\n2. return से जुड़े reminders देखें.\n3. alert से return स्क्रीन खोलें या handled मार्क करें.",
        ),
        make_entry(
            "settings_data_satpuda_ai_enable",
            ["settings_data"],
            ["satpuda ai", "enable ai", "AI सुरू", "AI चालू करें", "सटपुडा एआय"],
            "1. Open Settings Data.\n2. Turn on Satpuda AI enable toggle.\n3. Save settings and test one help query.",
            "1. Settings Data उघडा.\n2. Satpuda AI enable टॉगल चालू करा.\n3. सेटिंग सेव्ह करून एक मदत प्रश्न तपासा.",
            "1. Settings Data खोलें.\n2. Satpuda AI enable टॉगल चालू करें.\n3. सेटिंग सेव करके एक मदद प्रश्न जांचें.",
        ),
        make_entry(
            "settings_data_export_all",
            ["settings_data"],
            ["export all", "backup all", "सर्व निर्यात", "सभी निर्यात", "full export"],
            "1. Open Settings Data.\n2. Click Export All.\n3. Choose location and wait for export completion.",
            "1. Settings Data उघडा.\n2. Export All क्लिक करा.\n3. जागा निवडा आणि export पूर्ण होईपर्यंत थांबा.",
            "1. Settings Data खोलें.\n2. Export All क्लिक करें.\n3. स्थान चुनें और export पूरा होने तक प्रतीक्षा करें.",
        ),
        make_entry(
            "settings_data_gemini_key",
            ["settings_data"],
            ["gemini key", "api key", "जेमिनी की", "जेमिनी कुंजी", "ai key"],
            "1. Open Settings Data AI section.\n2. Paste Gemini API key in key field.\n3. Save and run a quick AI check.",
            "1. Settings Data च्या AI विभागात जा.\n2. Gemini API key फील्डमध्ये पेस्ट करा.\n3. सेव्ह करून AI तपासणी करा.",
            "1. Settings Data के AI सेक्शन में जाएं.\n2. Gemini API key फ़ील्ड में पेस्ट करें.\n3. सेव करें और AI जांच चलाएँ.",
        ),
        make_entry(
            "settings_data_voice_vs_ai",
            ["settings_data"],
            ["voice vs ai", "voice mode", "व्हॉइस", "आवाज मोड", "ai mode"],
            "1. Open Settings Data assistant options.\n2. Select Voice mode for spoken guidance or AI mode for text help.\n3. Save preference and test once.",
            "1. Settings Data मधील assistant options उघडा.\n2. बोलक्या मार्गदर्शनासाठी Voice mode किंवा मजकूरासाठी AI mode निवडा.\n3. निवड सेव्ह करून एकदा तपासा.",
            "1. Settings Data के assistant options खोलें.\n2. बोलकर मार्गदर्शन के लिए Voice mode या टेक्स्ट मदद के लिए AI mode चुनें.\n3. पसंद सेव करें और एक बार जांचें.",
        ),
        make_entry(
            "settings_pharmacy",
            ["settings_pharmacy"],
            ["pharmacy settings", "store profile", "फार्मसी सेटिंग", "दुकान प्रोफाइल", "shop details"],
            "1. Open Settings Pharmacy.\n2. Update shop name, license, GST and address.\n3. Save to use updated details in bills and reports.",
            "1. Settings Pharmacy उघडा.\n2. दुकानाचे नाव, परवाना, GST आणि पत्ता अपडेट करा.\n3. सेव्ह केल्यावर बिले आणि रिपोर्टमध्ये तपशील अपडेट होतात.",
            "1. Settings Pharmacy खोलें.\n2. दुकान का नाम, लाइसेंस, GST और पता अपडेट करें.\n3. सेव करने पर बिल और रिपोर्ट में विवरण अपडेट होंगे.",
        ),
        make_entry(
            "settings_contacts",
            ["settings_contacts"],
            ["contacts settings", "contact list", "संपर्क", "कॉन्टैक्ट", "phonebook"],
            "1. Open Settings Contacts.\n2. Add or edit important phone contacts.\n3. Save contact list for quick access.",
            "1. Settings Contacts उघडा.\n2. महत्त्वाचे फोन संपर्क जोडा किंवा बदला.\n3. जलद वापरासाठी सूची सेव्ह करा.",
            "1. Settings Contacts खोलें.\n2. जरूरी फोन संपर्क जोड़ें या संपादित करें.\n3. तेज उपयोग के लिए सूची सेव करें.",
        ),
        make_entry(
            "settings_import",
            ["settings_import"],
            ["import settings", "data import", "इम्पोर्ट", "आयात", "load data"],
            "1. Open Settings Import.\n2. Select valid import file.\n3. Run import and verify summary.",
            "1. Settings Import उघडा.\n2. योग्य import फाइल निवडा.\n3. import चालवून summary तपासा.",
            "1. Settings Import खोलें.\n2. सही import फ़ाइल चुनें.\n3. import चलाकर summary जांचें.",
        ),
        make_entry(
            "settings_layout",
            ["settings_layout"],
            ["layout settings", "screen layout", "लेआउट", "स्क्रीन लेआउट", "ui layout"],
            "1. Open Settings Layout.\n2. Choose preferred layout options.\n3. Save and reopen screen to confirm layout.",
            "1. Settings Layout उघडा.\n2. आवडती layout पर्याय निवडा.\n3. सेव्ह करून स्क्रीन परत उघडून तपासा.",
            "1. Settings Layout खोलें.\n2. पसंदीदा layout विकल्प चुनें.\n3. सेव करके स्क्रीन दोबारा खोलकर जांचें.",
        ),
        make_entry(
            "settings_sales_billing",
            ["settings_sales_billing"],
            ["sales billing settings", "billing setup", "बिलिंग सेटिंग", "बिलिंग सेटअप", "invoice settings"],
            "1. Open Settings Sales Billing.\n2. Configure invoice, tax and print preferences.\n3. Save settings and test with one sample bill.",
            "1. Settings Sales Billing उघडा.\n2. invoice, tax आणि print पर्याय सेट करा.\n3. सेटिंग सेव्ह करून एक नमुना बिल तपासा.",
            "1. Settings Sales Billing खोलें.\n2. invoice, tax और print विकल्प सेट करें.\n3. सेटिंग सेव करके एक नमूना बिल जांचें.",
        ),
        make_entry(
            "settings_shelf",
            ["settings_shelf"],
            ["shelf settings", "rack mapping", "शेल्फ", "रैक", "shelf map"],
            "1. Open Settings Shelf.\n2. Add or edit shelf and rack names.\n3. Save to use shelf mapping in inventory.",
            "1. Settings Shelf उघडा.\n2. shelf आणि rack नावे जोडा किंवा बदला.\n3. inventory साठी shelf mapping सेव्ह करा.",
            "1. Settings Shelf खोलें.\n2. shelf और rack नाम जोड़ें या बदलें.\n3. inventory के लिए shelf mapping सेव करें.",
        ),
        make_entry(
            "settings_shortcuts",
            ["settings_shortcuts"],
            ["keyboard shortcuts", "shortcuts", "शॉर्टकट", "किबोर्ड शॉर्टकट", "एफ5 सेव"],
            "1. Open Settings Shortcuts.\n2. Review keys like F5 for Save.\n3. Practice the shortcut on a test entry.",
            "1. Settings Shortcuts उघडा.\n2. Save साठी F5 सारख्या कळा तपासा.\n3. test एंट्रीवर shortcut वापरून पाहा.",
            "1. Settings Shortcuts खोलें.\n2. Save के लिए F5 जैसे keys देखें.\n3. test एंट्री पर shortcut उपयोग करके देखें.",
        ),
        make_entry(
            "home_new_purchase",
            ["home", "purchase"],
            ["home purchase", "new purchase", "नवी खरेदी", "नई खरीद", "purchase from home"],
            "1. Open Home screen.\n2. Click New Purchase.\n3. Purchase screen opens for immediate supplier entry.",
            "1. Home स्क्रीन उघडा.\n2. New Purchase क्लिक करा.\n3. लगेच पुरवठादार एंट्रीसाठी Purchase स्क्रीन उघडते.",
            "1. Home स्क्रीन खोलें.\n2. New Purchase क्लिक करें.\n3. तुरंत सप्लायर एंट्री के लिए Purchase स्क्रीन खुलती है.",
        ),
        make_entry(
            "home_new_bill",
            ["home", "sales_billing"],
            ["home new bill", "new bill", "नवे बिल", "नया बिल", "bill from home"],
            "1. Open Home screen.\n2. Click New Bill.\n3. Sales Billing opens for quick billing.",
            "1. Home स्क्रीन उघडा.\n2. New Bill क्लिक करा.\n3. जलद बिलिंगसाठी Sales Billing उघडते.",
            "1. Home स्क्रीन खोलें.\n2. New Bill क्लिक करें.\n3. तेज बिलिंग के लिए Sales Billing खुलता है.",
        ),
        make_entry(
            "home_export",
            ["home"],
            ["home export", "quick export", "होम एक्सपोर्ट", "होम निर्यात", "export"],
            "1. Open Home screen.\n2. Click Export shortcut.\n3. Select export type and save output file.",
            "1. Home स्क्रीन उघडा.\n2. Export शॉर्टकट क्लिक करा.\n3. export प्रकार निवडून फाइल सेव्ह करा.",
            "1. Home स्क्रीन खोलें.\n2. Export शॉर्टकट क्लिक करें.\n3. export प्रकार चुनकर फ़ाइल सेव करें.",
        ),
        make_entry(
            "home_alerts",
            ["home", "settings_alerts"],
            ["home alerts", "alert panel", "अलर्ट", "चेतावनी", "notifications"],
            "1. Open Home screen.\n2. Click Alerts panel.\n3. Open related task or mark alert handled.",
            "1. Home स्क्रीन उघडा.\n2. Alerts पॅनेल क्लिक करा.\n3. संबंधित काम उघडा किंवा alert handled करा.",
            "1. Home स्क्रीन खोलें.\n2. Alerts पैनल क्लिक करें.\n3. संबंधित काम खोलें या alert handled करें.",
        ),
        make_entry(
            "home_ledger",
            ["home", "settings_ledger"],
            ["home ledger", "ledger shortcut", "लेजर", "खाता", "ledger from home"],
            "1. Open Home screen.\n2. Click Ledger shortcut.\n3. Review dues, balances, and recent movements.",
            "1. Home स्क्रीन उघडा.\n2. Ledger शॉर्टकट क्लिक करा.\n3. बाकी रक्कम, शिल्लक आणि अलीकडील हालचाली तपासा.",
            "1. Home स्क्रीन खोलें.\n2. Ledger शॉर्टकट क्लिक करें.\n3. बकाया, बैलेंस और हाल की एंट्री देखें.",
        ),
        make_entry(
            "general_products",
            ["general_products", "inventory"],
            ["general products", "non medicine", "जनरल प्रॉडक्ट", "सामान्य उत्पाद", "ओटीसी"],
            "1. Open General Products section.\n2. Add or edit non-medicine items with rate and stock.\n3. Save to use products in billing and inventory.",
            "1. General Products विभाग उघडा.\n2. non-medicine आयटम दर आणि स्टॉकसह जोडा किंवा बदला.\n3. सेव्ह केल्यावर हे products बिलिंग आणि inventory मध्ये वापरता येतात.",
            "1. General Products सेक्शन खोलें.\n2. non-medicine आइटम रेट और स्टॉक के साथ जोड़ें या संपादित करें.\n3. सेव करने पर ये products बिलिंग और inventory में उपयोग होंगे.",
        ),
    ]
    return entries


def build_payload() -> dict[str, Any]:
    entries = build_entries()
    if len(entries) < 48:
        raise ValueError("Expected at least 48 FAQ entries.")
    return {"version": 1, "entries": entries}


def main() -> Path:
    repo_root = Path(__file__).resolve().parent.parent
    out_path = repo_root / "docs" / "app_help" / "offline_faq.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = build_payload()
    out_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(payload['entries'])} entries to {out_path}")
    print(f"Size: {out_path.stat().st_size} bytes")
    return out_path


if __name__ == "__main__":
    main()
